apiVersion: v1
kind: Pod
metadata:
  name: readonly-pod
spec:
  containers:
    - name: readonly-container
      image: nginx:1.29
      ports:
        - containerPort: 8080
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        allowPrivilegeEscalation: false
      volumeMounts:
        - name: tmp-vol
          mountPath: /tmp
        - name: var-run
          mountPath: /var/run
        - name: var-cache
          mountPath: /var/cache/nginx
        - name: var-log
          mountPath: /var/log/nginx
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
  volumes:
    - name: tmp-vol
      emptyDir: { }
    - name: var-run
      emptyDir: { }
    - name: var-cache
      emptyDir: { }
    - name: var-log
      emptyDir: { }
    - name: nginx-conf
      configMap:
        name: nginx-readonly-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-readonly-config
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
