apiVersion: v1
kind: Pod
metadata:
  name: crash-pod
spec:
  containers:
    - name: crash-container
      image: busybox:1.28
      command: [ "/bin/sh", "-c", "echo 'Starting...'; sleep 10; echo 'Crashing now!'; exit 1" ]
      resources:
        requests:
          memory: "32Mi"
          cpu: "100m"
        limits:
          memory: "64Mi"
          cpu: "200m"
