apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  completions: 5
  parallelism: 2
  completionMode: Indexed
  template:
    spec:
      containers:
        - name: worker
          image: busybox:1.28
          command:
            - sh
            - -c
            - |
              index=${JOB_COMPLETION_INDEX:-0}
              echo "Worker $index: Starting processing"
              sleep $((3 + RANDOM % 5))
              echo "Worker $index: Processing completed"
      restartPolicy: Never
