apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
    - name: nginx
      image: nginx:1.29
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: uploads
          mountPath: /data/uploads
        - name: logs
          mountPath: /var/log/nginx
    - name: log-processor
      image: busybox:1.28
      command: [ "/bin/sh", "-c" ]
      args:
        - |
          while true; do
            if [ -f /logs/access.log ]; then
              echo "Processing access logs..."
              grep -E "(POST|PUT)" /logs/access.log | tail -5 >> /logs/uploads.log 2>/dev/null || true
            fi
            sleep 10
          done
      volumeMounts:
        - name: logs
          mountPath: /logs
  volumes:
    - name: config
      configMap:
        name: webapp-config
    - name: uploads
      persistentVolumeClaim:
        claimName: uploads-pvc
    - name: logs
      emptyDir: { }
