apiVersion: v1
kind: Pod
metadata:
  name: app-with-env
spec:
  containers:
    - name: app
      image: nginx:1.29
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
      envFrom:
        - secretRef:
            name: db-credentials
