apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        environment: staging
    spec:
      containers:
        - name: myapp
          image: nginx:1.29
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: staging
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
