apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: container-1
      image: busybox:1.28
      command: [ "/bin/sh", "-c" ]
      args:
        - |
          echo "Container 1 started" > /shared/from-container-1.txt
          while true; do
            echo "$(date): Hello from container 1" >> /shared/from-container-1.txt
            sleep 30
          done
      volumeMounts:
        - name: shared-volume
          mountPath: /shared
    - name: container-2
      image: busybox:1.28
      command: [ "/bin/sh", "-c" ]
      args:
        - |
          sleep 10
          while true; do
            echo "=== Container 2 reading files ==="
            ls -la /shared/
            if [ -f /shared/from-container-1.txt ]; then
              echo "Content from container 1:"
              cat /shared/from-container-1.txt
            fi
            sleep 30
          done
      volumeMounts:
        - name: shared-volume
          mountPath: /shared
  volumes:
    - name: shared-volume
      emptyDir: { }
