apiVersion: v1
kind: Pod
metadata:
  name: web-pod-advanced
spec:
  initContainers:
    - name: init-service-check
      image: curlimages/curl:7.85.0
      command: [ 'sh', '-c' ]
      args:
        - |
          until curl -f http://backend-service.default.svc.cluster.local; do
            echo "Waiting for backend service to respond"
            sleep 5
          done
          echo "Backend service is ready!"
  containers:
    - name: web-app
      image: nginx:1.29
      ports:
        - containerPort: 80
